export enum DeploymentImportResolutionPolicy {
  OVERWRITE = 'OVERWRITE',
  SKIP_IF_EXISTS = 'SKIP_IF_EXISTS',
}

export enum ValidationState {
  VALIDATED = 'VALIDATED',
  FAILED = 'FAILED',
}

export enum ExportConfigComponentType {
  MCP_DEPLOYMENT = 'MCP_DEPLOYMENT',
  ADAPTER_DEPLOYMENT = 'ADAPTER_DEPLOYMENT',
  APPLICATION_DEPLOYMENT = 'APPLICATION_DEPLOYMENT',
  INTERCEPTOR_DEPLOYMENT = 'INTERCEPTOR_DEPLOYMENT',
  NIM_DEPLOYMENT = 'NIM_DEPLOYMENT',
  INFERENCE_DEPLOYMENT = 'INFERENCE_DEPLOYMENT',
  MCP_IMAGE_DEFINITION = 'MCP_IMAGE_DEFINITION',
  ADAPTER_IMAGE_DEFINITION = 'ADAPTER_IMAGE_DEFINITION',
  APPLICATION_IMAGE_DEFINITION = 'APPLICATION_IMAGE_DEFINITION',
  INTERCEPTOR_IMAGE_DEFINITION = 'INTERCEPTOR_IMAGE_DEFINITION',
  GLOBAL_DOMAIN_WHITELIST = 'GLOBAL_DOMAIN_WHITELIST',
}

export interface ValidationError {
  entityType: string;
  entityIdentifier: string;
  fieldPath: string;
  message: string;
}
