import { SortDirectionDto } from '@/src/types/request';

export const sorts = [
  {
    column: 'id',
    direction: SortDirectionDto.DESC,
  },
];

export enum EntityParameterKeys {
  TOPICS = 'topics',
  HASHING_ORDER = 'fieldsHashingOrder',
  LIMITS = 'limits',
  PRICING = 'pricing',
  INTERCEPTORS = 'interceptors',
  ROLES = 'roles',
  ROLE_LIMITS = 'roleLimits',
  DEFAULT_ROLE_LIMIT = 'defaultRoleLimit',
  UPSTREAMS = 'upstreams',
  FEATURES = 'features',
  ENABLED = 'enabled',
  PROPERTIES = 'properties',
  PATHS = 'paths',
  METHODS = 'methods',
  RESPONSE = 'response',
  APPLICATIONS = 'applications',
  ENTITIES = 'entities',
  DEFS = '$defs',
  KEYS = 'grantedKeys',
  PARAMETERS = 'parameters',
  MODELS = 'models',
  UNIT = 'unit',
  DEPENDENCIES = 'dependencies',
}

export enum ParameterNamesI18nKey {
  roleLimits = 'ParameterNames.roleLimits',
  isPublic = 'ParameterNames.isPublic',
  defaultRoleLimit = 'ParameterNames.defaultRoleLimit',
  fieldsHashingOrder = 'ParameterNames.fieldsHashingOrder',
  endpointDeploymentName = 'ParameterNames.endpointDeploymentName',
  name = 'ParameterNames.name',
  author = 'ParameterNames.author',
  endpoint = 'ParameterNames.endpoint',
  displayName = 'ParameterNames.displayName',
  displayVersion = 'ParameterNames.displayVersion',
  adapter = 'ParameterNames.adapter',
  iconUrl = 'ParameterNames.iconUrl',
  description = 'ParameterNames.description',
  forwardAuthToken = 'ParameterNames.forwardAuthToken',
  features = 'ParameterNames.features',
  inputAttachmentTypes = 'ParameterNames.inputAttachmentTypes',
  maxInputAttachments = 'ParameterNames.maxInputAttachments',
  defaults = 'ParameterNames.defaults',
  topics = 'ParameterNames.topics',
  maxRetryAttempts = 'ParameterNames.maxRetryAttempts',
  type = 'ParameterNames.type',
  tokenizerModel = 'ParameterNames.tokenizerModel',
  limits = 'ParameterNames.limits',
  maxTotalTokens = 'ParameterNames.maxTotalTokens',
  pricing = 'ParameterNames.pricing',
  unit = 'ParameterNames.unit',
  prompt = 'ParameterNames.prompt',
  completion = 'ParameterNames.completion',
  upstreams = 'ParameterNames.upstreams',
  key = 'ParameterNames.key',
  weight = 'ParameterNames.weight',
  tier = 'ParameterNames.tier',
  overrideName = 'ParameterNames.overrideName',
  properties = 'ParameterNames.properties',
  enabled = 'ParameterNames.enabled',
  minute = 'ParameterNames.minute',
  day = 'ParameterNames.day',
  week = 'ParameterNames.week',
  month = 'ParameterNames.month',
  interceptors = 'ParameterNames.interceptors',
  roles = 'ParameterNames.roles',
  paths = 'ParameterNames.paths',
  methods = 'ParameterNames.methods',
  status = 'ParameterNames.status',
  body = 'ParameterNames.body',
  $defs = 'ParameterNames.$defs',
  $id = 'ParameterNames.$id',
  $schema = 'ParameterNames.$schema',
  applications = 'ParameterNames.applications',
  entities = 'ParameterNames.entities',
  'dial:applicationTypeCompletionEndpoint' = 'ParameterNames.applicationTypeCompletionEndpoint',
  'dial:applicationTypeDisplayName' = 'ParameterNames.applicationTypeDisplayName',
  title = 'ParameterNames.title',
  'dial:applicationTypeEditorUrl' = 'ParameterNames.applicationTypeEditorUrl',
  'dial:applicationTypeViewerUrl' = 'ParameterNames.applicationTypeViewerUrl',
  'dial:applicationTypeConfigurationEndpoint' = 'ParameterNames.applicationTypeConfigurationEndpoint',
  'dial:applicationTypeRateEndpoint' = 'ParameterNames.applicationTypeRateEndpoint',
  'dial:applicationTypeTokenizeEndpoint' = 'ParameterNames.applicationTypeTokenizeEndpoint',
  'dial:applicationTypeTruncatePromptEndpoint' = 'ParameterNames.applicationTypeTruncatePromptEndpoint',
  'dial:appendApplicationPropertiesHeader' = 'ParameterNames.appendApplicationPropertiesHeader',
  grantedKeys = 'ParameterNames.grantedKeys',
  createdAt = 'ParameterNames.createdAt',
  updatedAt = 'ParameterNames.updatedAt',
  expiresAt = 'ParameterNames.expiresAt',
  keyGeneratedAt = 'ParameterNames.keyGeneratedAt',
  project = 'ParameterNames.project',
  projectContactPoint = 'ParameterNames.projectContactPoint',
  secured = 'ParameterNames.secured',
  parameters = 'ParameterNames.parameters',
  extraData = 'ParameterNames.extraData',
  models = 'ParameterNames.models',
  baseEndpoint = 'ParameterNames.baseEndpoint',
  dependencies = 'ParameterNames.dependencies',
}
