import {
  Icon,
  IconActivity,
  IconApps,
  IconAppWindow,
  IconBolt,
  IconBox,
  IconBraces,
  IconListDetails,
  IconDatabase,
  IconFile,
  IconFilter,
  IconFolder,
  IconHistory,
  IconKey,
  IconLanguage,
  IconLayoutDashboard,
  IconListCheck,
  IconMessage,
  IconPlayerPlay,
  IconPlug,
  IconPrompt,
  IconRoute,
  IconServer,
  IconSparkles,
  IconStack2,
  IconTable,
  IconTimeline,
  IconTool,
  IconUsers,
  IconZoomCode,
} from '@tabler/icons-react';

import { MenuI18nKey } from '@/src/constants/i18n';

// Pages without their own icon reuse the icon of the page they mirror (Catalog, Approvals, Deployments).
export const MENU_ITEM_ICONS: Partial<Record<MenuI18nKey, Icon>> = {
  [MenuI18nKey.Models]: IconSparkles,
  [MenuI18nKey.PlatformModels]: IconSparkles,
  [MenuI18nKey.Toolsets]: IconTool,
  [MenuI18nKey.ToolsetPublications]: IconTool,
  [MenuI18nKey.PlatformTranslators]: IconLanguage,
  [MenuI18nKey.Routes]: IconRoute,
  [MenuI18nKey.PlatformRoutes]: IconRoute,
  [MenuI18nKey.Applications]: IconApps,
  [MenuI18nKey.ApplicationPublications]: IconApps,
  [MenuI18nKey.ApplicationRunners]: IconAppWindow,
  [MenuI18nKey.PlatformAppRunners]: IconAppWindow,
  [MenuI18nKey.PlatformCatalogSchemas]: IconBraces,
  [MenuI18nKey.Skills]: IconBolt,
  [MenuI18nKey.SkillPublications]: IconBolt,
  [MenuI18nKey.Files]: IconFile,
  [MenuI18nKey.FilePublications]: IconFile,
  [MenuI18nKey.Conversations]: IconMessage,
  [MenuI18nKey.ConversationPublications]: IconMessage,
  [MenuI18nKey.Prompts]: IconPrompt,
  [MenuI18nKey.PromptPublications]: IconPrompt,
  [MenuI18nKey.ModelServings]: IconServer,
  [MenuI18nKey.McpContainers]: IconBox,
  [MenuI18nKey.InterceptorContainers]: IconBox,
  [MenuI18nKey.AdapterContainers]: IconBox,
  [MenuI18nKey.ApplicationContainers]: IconBox,
  [MenuI18nKey.Images]: IconStack2,
  [MenuI18nKey.TestSuites]: IconListCheck,
  [MenuI18nKey.Runs]: IconPlayerPlay,
  [MenuI18nKey.Datasets]: IconDatabase,
  [MenuI18nKey.Dashboard]: IconLayoutDashboard,
  [MenuI18nKey.Queries]: IconZoomCode,
  [MenuI18nKey.AnalyticsSessions]: IconActivity,
  [MenuI18nKey.Tables]: IconTable,
  [MenuI18nKey.Pipelines]: IconTimeline,
  [MenuI18nKey.Roles]: IconUsers,
  [MenuI18nKey.PlatformRoles]: IconUsers,
  [MenuI18nKey.Keys]: IconKey,
  [MenuI18nKey.PlatformKeys]: IconKey,
  [MenuI18nKey.FoldersStorage]: IconFolder,
  [MenuI18nKey.Interceptors]: IconFilter,
  [MenuI18nKey.InterceptorTemplates]: IconFilter,
  [MenuI18nKey.PlatformInterceptors]: IconFilter,
  [MenuI18nKey.Adapters]: IconPlug,
  [MenuI18nKey.ActivityAudit]: IconHistory,
  [MenuI18nKey.UsageLog]: IconListDetails,
};
