export enum ActionMenuOperation {
  Delete = 'Delete',
  Duplicate = 'Duplicate',
  Open_in_new_tab = 'Open in a new tab',
  Remove = 'Remove',
  Reset_to_default_limits = 'Reset to default limits',
  Set_no_limits = 'Set unlimited',
  Move = 'Move to another folders',
  Publish = 'Publish',
  Unpublish = 'Unpublish',
  Decline = 'Decline',
  Download = 'Download',
  Preview = 'Preview',
  Resource_rollback = 'Resource rollback',
  View_details = 'View details',
  Add_child = 'Add child',
  Add_sibling = 'Add sibling',
  Manage_folder = 'Manage permissions',
  Rename = 'Rename',
  Move_to = 'Move to',
  Compare_changes = 'Compare changes',
  Install = 'Install',
  Run = 'Run',
  Stop = 'Stop',
  CreateNewVersion = 'Create new version',
  Try_out = 'Try out',
  Edit = 'Edit',
}
