export enum EntityType {
  ENTITIES = 'ENTITIES',
  MODEL = 'MODEL',
  APPLICATION = 'APPLICATION',
  ROUTE = 'ROUTE',
  ROLE = 'ROLE',
  KEY = 'KEY',
  INTERCEPTOR = 'INTERCEPTOR',
  APPLICATION_TYPE_SCHEMA = 'APPLICATION_TYPE_SCHEMA',
  ADAPTER = 'ADAPTER',
  PROMPT = 'PROMPT',
  FILE = 'FILE',
}
