export enum ResourceType {
  FILE = 'FILE',
  PROMPT = 'PROMPT',
  APPLICATION = 'APPLICATION',
  TOOLSET = 'TOOL_SET',
  CONVERSATION = 'CONVERSATION',
  MODEL = 'MODEL',
  APP_TYPE_SCHEMA = 'APP_TYPE_SCHEMA',
}
