export enum ApplicationRoute {
  Home = '/home',
  Models = '/models',
  Adapters = '/adapters',
  Applications = '/applications',
  AssetsApplications = '/assets-applications',
  ApplicationRunners = '/application-runners',
  ApplicationPublications = '/application-publications',
  Interceptors = '/interceptors',
  Roles = '/roles',
  Keys = '/keys',
  Prompts = '/prompts',
  Files = '/files',
  Routes = '/routes',
  Dashboard = '/dashboard',
  UsageLog = '/usage-log',
  PromptPublications = '/publications-prompt',
  FilePublications = '/publications-file',
  ImportConfig = '/import-config',
  ExportConfig = '/export-config',
  FoldersStorage = '/folders-storage',
  ActivityAudit = '/activity-audit',
  Forbidden = '/forbidden',
  InterceptorTemplates = '/interceptor-templates',
  InterceptorDeployments = '/interceptor-deployments',
}
