enum MimeType {
  JSON = 'application/json',
  XML = 'application/xml',
  HTML = 'application/html',
  CSV = 'application/csv',
  TEXT_JSON = 'text/json',
  TEXT_XML = 'text/xml',
  TEXT_HTML = 'text/html',
  TEXT_CSV = 'text/csv',
  MARKDOWN = 'text/markdown',
  PLAIN_TEXT = 'text/plain',
  CSS = 'text/css',
  JAVASCRIPT = 'text/javascript',
  PDF = 'application/pdf',

  APNG = 'image/apng',
  AVIF = 'image/avif',
  BMP = 'image/bmp',
  GIF = 'image/gif',
  ICO = 'image/vnd.microsoft.icon',
  JPEG = 'image/jpeg',
  PNG = 'image/png',
  SVG = 'image/svg+xml',
  TIFF = 'image/tiff',
  WEBP = 'image/webp',
  X_ICON = 'image/x-icon',

  DOC = 'application/msword',
  DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  PDB = 'chemical/x-pdb',
  PLOTLY = 'application/vnd.plotly.v1+json',
  PPT = 'application/vnd.ms-powerpoint',
  PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  TTYD_TABLE = 'application/dial-ttyd-table',
  UNKNOWN_BINARY = 'application/octet-stream',
  XLS = 'application/vnd.ms-excel',
  XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
}

export const mimeMapping = [
  { label: 'gif', value: MimeType.GIF },
  { label: 'png', value: MimeType.PNG },
  { label: 'jpg', value: MimeType.JPEG },
  { label: 'tiff', value: MimeType.TIFF },

  { label: 'json', value: MimeType.JSON },
  { label: 'xml', value: MimeType.XML },
  { label: 'html', value: MimeType.HTML },
  { label: 'csv', value: MimeType.CSV },
  { label: 'text-json', value: MimeType.TEXT_JSON },
  { label: 'text-xml', value: MimeType.TEXT_XML },
  { label: 'text-html', value: MimeType.TEXT_HTML },
  { label: 'text-csv', value: MimeType.TEXT_CSV },
  { label: 'markdown', value: MimeType.MARKDOWN },
  { label: 'plain-text', value: MimeType.PLAIN_TEXT },
  { label: 'css', value: MimeType.CSS },
  { label: 'javascript', value: MimeType.JAVASCRIPT },
  { label: 'pdf', value: MimeType.PDF },
  { label: 'xml-old', value: MimeType.TEXT_XML },

  { label: 'apng', value: MimeType.APNG },
  { label: 'avif', value: MimeType.AVIF },
  { label: 'bmp', value: MimeType.BMP },
  { label: 'ico', value: MimeType.ICO },
  { label: 'svg', value: MimeType.SVG },
  { label: 'webp', value: MimeType.WEBP },
  { label: 'x-icon', value: MimeType.X_ICON },

  { label: 'doc', value: MimeType.DOC },
  { label: 'docx', value: MimeType.DOCX },
  { label: 'pdb', value: MimeType.PDB },
  { label: 'plotly', value: MimeType.PLOTLY },
  { label: 'ppt', value: MimeType.PPT },
  { label: 'pptx', value: MimeType.PPTX },
  { label: 'ttyd-table', value: MimeType.TTYD_TABLE },
  { label: 'unknown-binary', value: MimeType.UNKNOWN_BINARY },
  { label: 'xls', value: MimeType.XLS },
  { label: 'xlsx', value: MimeType.XLSX },
];
