const MIME_TYPES = {
  JSON: 'application/json',
  XML: 'application/xml',
  HTML: 'application/html',
  CSV: 'application/csv',
  TEXT_JSON: 'text/json',
  TEXT_XML: 'text/xml',
  TEXT_HTML: 'text/html',
  TEXT_CSV: 'text/csv',
  MARKDOWN: 'text/markdown',
  PLAIN_TEXT: 'text/plain',
  CSS: 'text/css',
  JAVASCRIPT: 'text/javascript',
  PDF: 'application/pdf',
  XML_OLD: 'text/xml',

  APNG: 'image/apng',
  AVIF: 'image/avif',
  BMP: 'image/bmp',
  GIF: 'image/gif',
  ICO: 'image/vnd.microsoft.icon',
  JPEG: 'image/jpeg',
  PNG: 'image/png',
  SVG: 'image/svg+xml',
  TIFF: 'image/tiff',
  WEBP: 'image/webp',
  X_ICON: 'image/x-icon',

  DOC: 'application/msword',
  DOCX: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  PDB: 'chemical/x-pdb',
  PLOTLY: 'application/vnd.plotly.v1+json',
  PPT: 'application/vnd.ms-powerpoint',
  PPTX: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  TTYD_TABLE: 'application/dial-ttyd-table',
  UNKNOWN_BINARY: 'application/octet-stream',
  XLS: 'application/vnd.ms-excel',
  XLSX: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
};

export const mimeMapping = [
  { label: 'gif', value: 'image/gif' },
  { label: 'png', value: 'image/png' },
  { label: 'jpg', value: 'image/jpeg' },
  { label: 'tiff', value: 'image/tiff' },

  { label: 'json', value: MIME_TYPES.JSON },
  { label: 'xml', value: MIME_TYPES.XML },
  { label: 'html', value: MIME_TYPES.HTML },
  { label: 'csv', value: MIME_TYPES.CSV },
  { label: 'text-json', value: MIME_TYPES.TEXT_JSON },
  { label: 'text-xml', value: MIME_TYPES.TEXT_XML },
  { label: 'text-html', value: MIME_TYPES.TEXT_HTML },
  { label: 'text-csv', value: MIME_TYPES.TEXT_CSV },
  { label: 'markdown', value: MIME_TYPES.MARKDOWN },
  { label: 'plain-text', value: MIME_TYPES.PLAIN_TEXT },
  { label: 'css', value: MIME_TYPES.CSS },
  { label: 'javascript', value: MIME_TYPES.JAVASCRIPT },
  { label: 'pdf', value: MIME_TYPES.PDF },
  { label: 'xml-old', value: MIME_TYPES.XML_OLD },

  { label: 'apng', value: MIME_TYPES.APNG },
  { label: 'avif', value: MIME_TYPES.AVIF },
  { label: 'bmp', value: MIME_TYPES.BMP },
  { label: 'ico', value: MIME_TYPES.ICO },
  { label: 'svg', value: MIME_TYPES.SVG },
  { label: 'webp', value: MIME_TYPES.WEBP },
  { label: 'x-icon', value: MIME_TYPES.X_ICON },

  { label: 'doc', value: MIME_TYPES.DOC },
  { label: 'docx', value: MIME_TYPES.DOCX },
  { label: 'pdb', value: MIME_TYPES.PDB },
  { label: 'plotly', value: MIME_TYPES.PLOTLY },
  { label: 'ppt', value: MIME_TYPES.PPT },
  { label: 'pptx', value: MIME_TYPES.PPTX },
  { label: 'ttyd-table', value: MIME_TYPES.TTYD_TABLE },
  { label: 'unknown-binary', value: MIME_TYPES.UNKNOWN_BINARY },
  { label: 'xls', value: MIME_TYPES.XLS },
  { label: 'xlsx', value: MIME_TYPES.XLSX },
];
