name: Release Workflow

on:
  push:
    branches: [development, release-*]
  workflow_dispatch:
    inputs:
      promote:
        type: boolean
        default: false
        description: Promote release to stable (for release-* branches only)

permissions:
  contents: write
  packages: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/node_release.yml@4.0.1
    with:
      promote: ${{ github.event_name == 'workflow_dispatch' && inputs.promote }}
      node-version: 24
      publish-enabled: false
      maximize-build-space: true
      ort-version: 85.0.0 # HACK: pin ORT version due to java.util.NoSuchElementException in 85.1.0
    secrets: inherit
